# Generated by Django 4.2 on 2024-07-03 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("a_posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
