# Generated by Django 4.2 on 2024-07-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_posts", "0004_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
